# Generated by Django 5.1.6 on 2025-02-22 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structural', '0002_project_element_project_node_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='project',
        ),
        migrations.RemoveField(
            model_name='node',
            name='project',
        ),
    ]
