# Generated by Django 5.1.6 on 2025-02-23 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structural', '0003_remove_element_project_remove_node_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='structural.node')),
                ('restrict_x', models.BooleanField(default=False)),
                ('restrict_y', models.BooleanField(default=False)),
                ('restrict_z', models.BooleanField(default=False)),
            ],
        ),
    ]
